import { APP_TYPE, EMAIL_VERIFICATION, MOBILE_VERIFICATION, USER_TYPES } from '../constants/app';
import { IDefaultAttributes } from './commanInterface';
export interface IUserAttributes extends IDefaultAttributes {
    id: string;
    uuid?: string;
    firstName: string;
    lastName: string;
    middleName?: string;
    emailVerification?: EMAIL_VERIFICATION;
    mobileVerification?: MOBILE_VERIFICATION;
    appType?: APP_TYPE;
    email: string;
    globalId?: string;
    mobile?: string;
    password?: string;
    type: USER_TYPES;
    address1?: string;
    address2?: string;
    gender?: string;
    dob?: Date;
    bloodGroup?: string;
    motherTongue?: string;
    otherLanguages?: string;
    degree?: string;
    college?: string;
    passingYear?: string;
    pinCode?: string;
    city?: number;
    state?: number;
    country?: number;
    roleId?: string;
    verificationOtp?: string;
    schoolName?: string;
    board?: string;
    medium?: string;
    standard?: string;
    stream?: string;
    schoolAddress?: string;
    // medicalHistory?: string;
    medications?: string;
    knownAllergies?: string;
    relation?: string;
    district?: string;
    area?: string;
    // profileImage?: string;
}
